 NumPy is a powerful tool for working with **Numbers** in Python.
  It's like a supercharged version of regular Python List designed to handle large Arrays of numbers efficiently.
  KEY ATTRIBUTES of NUMPY are Arrays , Mathematical Functions , Linear Algebra and Random Number Generation.
   We use NumPy for more Speed , more Efficiency and more Simplicity of coding.

00  **Create Array** 

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


01   .zero() To convert all values of an Array into zero as well as  .ones() works same

In [3]:
a=np.zeros([1,2,3,4,5])
print(a)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]]


02 .linspace()   "This method create required random numbers (num) between start(0) and end point(10)"

In [4]:
start : int = 0
stop : int = 10
num : int = 20
a=np.linspace(start,stop,num)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


03  .arange() "in this method we can set the space (2) between start (0) and end point(10)"

In [5]:
a  = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


 04   ARRAY MANIPULATION

In [6]:
# .RESHAPE() HAS TWO ATTRIBUTES 1st is ARRAY [1,2,3,4,5,6] / 2nd is DIMENSTION (3,2) (3 is rows , 2 is culomns)
a = np.reshape([1,2,3,4,5,6],(3,2))  
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
# .TRANSPOSE()  FILPPING the ROWS into  CULOMNS and columns into rows. there will be error if the quantity the values are not same of Arrays
my_arrays = np.array([[3,2,5] ,[4,5,9]])
a = np.transpose(my_arrays)
print(a)

[[3 4]
 [2 5]
 [5 9]]


In [8]:
#.CONCATENATE() #
# SIMPLE .CONCATENATE() ##
j = np.array([0,5])
a =np.array([1,2,3]) 
b =np.array([4,5,6]) 
c = np.concatenate((b,j,a))
print(c)

[4 5 6 0 5 1 2 3]


In [9]:
# Axis: You can optionally specify the axis parameter to control the direction of concatenation.#
#  By default (axis=0), it joins arrays vertically (row-wise). If you set axis=1, it joins them horizontally (column-wise) #
a1 =np.array([[1,2,3] , [11,22,33]]) 
b1 =np.array([[4,5,6] ,[44,55,66]]) 
c1 = np.concatenate((a1,b1) , axis = 1)
print(c1)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [10]:
# Axis: You can optionally specify the axis parameter to control the direction of concatenation.#
#  By default (axis=0), it joins arrays vertically (row-wise). If you set axis=1, it joins them horizontally (column-wise) #
a1 =np.array([[1,2,3] , [11,22,33]]) 
b1 =np.array([[4,5,6] ,[44,55,66]]) 
c1 = np.concatenate((a1,b1) , axis=0) 
print(c1)

[[ 1  2  3]
 [11 22 33]
 [ 4  5  6]
 [44 55 66]]


In [11]:
#.SPILT()
arr = np.array([1, 2, 3, 4, 5, 6])

# # Split into 3 equal-sized sub-arrays
sub_arrays = np.split(arr, 3)  
print(sub_arrays)  # Output: [array([1, 2]), array([3, 4]), array([5, 6])]

# # Split at specific indices
sub_arrays2 = np.split(arr, [2, 5])  
print(sub_arrays2)  # Output: [array([1, 2]), array([3, 4, 5]), array([6])]

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4, 5]), array([6])]


  05  MATHEMATICAL operations :

In [12]:
# np.add()
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.add(a,b)
print(c)

[5 7 9]


In [13]:
#np.subtract()
d = np.array([7,8,9])
e = np.array([3,5,7])
f = np.subtract(e,d)
print(f)

[-4 -3 -2]


In [14]:
# np.divide()
g = np.array([16,24,36])
h = np.array([4,5,6])
i = np.divide(g,h)
print(i)

[4.  4.8 6. ]


In [15]:
# np.multiply()
j = np.array([16,24,36])
k = np.array([4,5,6])
l = np.multiply(j,k)
print(l)

[ 64 120 216]


In [16]:
# np.sqrt()  //square root
r = np.array([81,67,49])
q = np.sqrt(r)
print(q)
# NOTE [9.         8.18535277 7.        ]
# The difference in position/spacing is purely a formatting choice by NumPy when displaying arrays in Google Colab's environment.

[9.         8.18535277 7.        ]


In [17]:
# np.exp()   //exponential of each element
my_numbers = [4, 5, 6]
exponential_results = np.exp(my_numbers) 
print(exponential_results)
#NOTE  e^
# Here's what's happening step-by-step:

# Your input: You provided the list [1, 2, 3] to the exp() function.

# The calculation: The exp() function takes each number in your list and calculates 'e' raised to the power of that number.
#  'e' is a special mathematical constant, approximately equal to 2.71828.

# The output: The output you see, [2.71828183, 7.3890561, 20.08553692], is the result of these calculations:

# e^1 (e raised to the power of 1) is approximately 2.71828183
# e^2 (e raised to the power of 2) is approximately 7.3890561
# e^3 (e raised to the power of 3) is approximately 20.08553692

[ 54.59815003 148.4131591  403.42879349]


05 Triggnomatric operation   # .log() / .sin() / .cos() / .tan()

In [18]:
a = [1,2,3]
alog = np.log(a)
print(f''' log of a :{alog}''')

b = [1,2,3]
bsin = np.sin(b)
print(f''' sin of b : {bsin}''')

c = [1,2,3]
ccos = np.cos(c)
print(f''' cos of c :{ccos}''')

d = [1,2,3]
dtan = np.tan(d)
print(f''' tan of d is {dtan}''')

 log of a :[0.         0.69314718 1.09861229]
 sin of b : [0.84147098 0.90929743 0.14112001]
 cos of c :[ 0.54030231 -0.41614684 -0.9899925 ]
 tan of d is [ 1.55740772 -2.18503986 -0.14254654]


06 STATISTICAL FUNCTIONS

In [19]:
# .mean()  Think of it like this: you have a bunch of test scores, and you want to find the average score.
#  You would add up all the scores and then divide by the total number of scores. That's exactly what .mean() does.
sd = [2,3,4,5,6]
sdm = np.mean(sd)
print(sdm)

4.0


In [20]:
#np.median()  How it works:

# Sort the numbers: Arrange the numbers in your dataset from smallest to largest.

# Find the middle value:

# If you have an odd number of values, the median is the value in the exact center of the sorted list.
# If you have an even number of values, the median is the average of the two values in the middle of the sorted list.

num = [2,3,9,5,6]   # odd number // Median: 4 (the middle value)
num_sort = np.sort(num)
print(num_sort)
num_mean = np.median(num)   # //  .meadian() automaticly first apply .sort() and then apply ,,meadian()
print(num_mean)

[2 3 5 6 9]
5.0


In [21]:
 # // ANOTHER WAY TO CODE //
num = [2,3,9,5,6]     
num_sort = np.sort(num)
print(num_sort)
num_mean = np.median(num_sort)
print(num_mean)

[2 3 5 6 9]
5.0


In [22]:
 # even number // Median: (3 + 5) / 2 = 4 (average of the two middle values)
num1 = [2,3,5,6]   
num_mean1 = np.median(num1)
print(num_mean1)

4.0


07  STANDARD DEVIATION  =  np.std()


 Here's how it works:
Calculate the Mean: np.std() first calculates the average of all the numbers in the array.
Find the Differences: It then finds the difference between each number and the average.
Square the Differences: These differences are squared to make them all positive (so negative and positive differences don't cancel each other out).
Calculate the Variance: The squared differences are averaged to find the variance, which is a measure of how spread out the numbers are.
Take the Square Root: Finally, np.std() takes the square root of the variance to get the standard deviation.

In [23]:
woo = [1,3,5,7,9]
wooo = np.std(woo)
print(wooo)

2.8284271247461903


  np.var()         The .var() function stands for variance.
  
It calculates the statistical variance of the data, which measures how spread out the values are from the mean (average).
In simple terms, it shows how much the numbers in your data differ from each other.
So, .var() = "variance."  // 1. What is variance?
Variance tells us how far the numbers are from the average.

In [24]:
voo = [1,2,3,4,5]
vooo = np.var(voo)
print(vooo)

2.0


In [25]:
# np.min()  &  np.max()  //  THIS FUNCTION FIND'S THE SMALLEST AND LARGEST NUMBER IN A DATASET , LIST ,ARRAY
mi = [188,23,43,67,86]
min = np.min(mi)
print(min)
max = np.max(mi)
print(max)

23
188


In [26]:
# np.sum()
su = [12,32,45,76]
sum = np.sum(su)
print(sum)

165


08        LINEAR ALGEBRA 

In [27]:
# np.dot()  What does np.dot() do?
# np.dot() performs the dot product of two arrays.
#  It's a way of combining two sets of numbers to produce a single value or a new matrix.
k = [2,4,6]    # EXPLAIN  //   2*1 + 4*3 + 6*5 =
h = [1,3,5]           # //      2+12+30  = 44
w = np.dot(k,h)       # //  output    .dot() = 44
print(w)

44


In [28]:
#  np.dot() {MATRICES}                          c:\Users\HC\AppData\Local\Microsoft\Windows\INetCache\IE\K50UQD5H\IMG-20241208-WA0058[1].jpg
k = np.array([[1,2] ,[3,4]])
h = np.array([[5,6] ,[7,8]])
w = np.dot(k,h)
print(w)

[[19 22]
 [43 50]]


  np.linalg.inv() is a NumPy function used to calculate the inverse of a square matrix.

In [29]:
a = np.array([[1,2] ,[3,4]])
aa = np.linalg.inv(a)       
print(aa) 
#  // Important Note:
# Not all matrices have inverses. If a matrix is singular (its determinant is zero),
#  it doesn't have an inverse. In such cases, np.linalg.inv() will raise a LinAlgError.

[[-2.   1. ]
 [ 1.5 -0.5]]


 np.linalg.det()      CALCULATE THE DETERMINANT : A determinant helps determine whether a matrix is invertible. if the determinant

In [30]:

b = np.array([[2,3] , [4,5]])                     #        is 0, the matrix is singular(non-invertible). 
bb = np.linalg.det(b) 
print(bb)

-2.0


 RANDOM NUMBER GENERATION :
 np.random.rand()  creates random numbers between 0 and 1  contains only +value

In [31]:
x = np.random.rand(2,3)
print(x)

[[0.02069996 0.01377977 0.98106186]
 [0.40842196 0.01253443 0.08963175]]


 np.random.randn      creates random numbers between 0 and 1  contains  +value or -value

In [32]:
xn = np.random.randn(3,3)
print(xn)

[[ 1.08527012  0.99253293 -0.71552263]
 [-0.19818673  0.92451759 -1.07511886]
 [-1.84998125 -0.88239977 -0.33765174]]


np.random.randint(low , high , size)

In [33]:
int = np.random.randint(2,20)
print(int)

17


In [34]:
int = np.random.randint(2,20, size=(2,3))
print(int)

[[18 17 19]
 [ 5 14  5]]
